apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jpetstore-hpa
  namespace: jpetstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jpetstore
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
